import { UserProvider } from "@/context/UserContext";
import "./globals.css";
import LayoutWrapper from "@/components/LayoutWrapper";
import { Flip, ToastContainer } from "react-toastify";



export const metadata = {
  title: "CCSCMS",
  description: "Generated by Saish Sachin Patil",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <UserProvider>
          <LayoutWrapper>
            <ToastContainer
              position="bottom-right"
              autoClose={1000}
              type="default"
              hideProgressBar={false}
              newestOnTop
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
              transition={Flip}
            />
            {children}
          </LayoutWrapper>
        </UserProvider>
      </body>
    </html>
  );
}
