import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { UserProvider } from "@/context/UserContext";
import "./globals.css";
import LayoutWrapper from "@/components/LayoutWrapper";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
      >
        <UserProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </UserProvider>
      </body>
    </html>
  );
}
