export const metadata = {
  title: "MECHANIC ccscms",
  description: "Generated by Saish Sachin Patil",
};

export default function DashboardLayout({ children }) {
  return (
    <section className="dashboard-container">
      {/* You can add a Sidebar or Navbar here */}
      <main>{children}</main>
    </section>
  );
}
