import DashboardMainWrapper from "./DashboardMainWrapper";
import { DashboardProvider } from "@/context/DashBoardContext";
export const metadata = {
  title: "Dashboard",
  description: "Generated by Saish Sachin Patil",
};

export default function DashboardLayout({ children }) {

  return (
    <DashboardProvider>
        <DashboardMainWrapper>{children}</DashboardMainWrapper>
    </DashboardProvider>
  );
}
